name: Benchmark PR

on:
  pull_request:
    paths: ["projects/**"]
    types: [opened, reopened, edited, synchronize]
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmarks:
    name: Run benchmarks for pr
    # runs-on: benchmarking-runner
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Stable Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install nodejs packages
        run: npm i

      - name: Install Wrk
        run: apt-get update && sudo apt-get install -y wrk

      - name: Run Cargo Build
        run: cargo run
